version: '3.8'
services:
  spark-master:
    image: bitnami/spark:latest
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master
    volumes:
      - ./src:/app/scripts
      - ./data:/app/data
    networks:
      - spark-network
  spark-worker:
    image: bitnami/spark:latest
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./src:/app/scripts
      - ./data:/app/data
    networks:
      - spark-network
networks:
  spark-network:
    driver: bridge